[package]
name = "kafka"
version = "0.2.0"
authors = ["Yousuf Fauzan"]
description = "Rust client for Apache Kafka"
homepage = "https://github.com/spicavigo/kafka-rust"
repository = "https://github.com/spicavigo/kafka-rust"
documentation = "https://spicavigo.github.io/kafka-rust/kafka/index.html"
readme = "README.md"
keywords = ["kafka", "queue"]
license = "MIT"


[dependencies]
byteorder = "0.4"
flate2 = "0.2"
crc = "1.2"
rsnappy = "0.1"
log = "0.3"

[dev-dependencies]
getopts = "0.2"
env_logger = "0.3"

[features]
nightly = []
